package tokenizer

import (
	"fmt"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// These body ids were generated by the pinned official
// PretrainedTextTokenizer at Aratako/Irodori-TTS-v4.1-Small revision
// 2b28324dc263ed5e6638b3cf3dd94c82ead07b4b, using the bundled tokenizer
// SHA256 6a0734cf21c802169defaffe719bc2ef12bb9d0be37e54b61ed27aa89394723d.
// The wrapper prepends BOS separately, so expected includes BOS below.
func TestV4OfficialFixtures(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(file), "../../../../model/irodori-v4.1/tokenizer/tokenizer.json")
	tok, err := FromFile(path, true)
	if err != nil {
		t.Fatal(err)
	}

	cases := []struct {
		name string
		text string
		want []int
	}{
		{"japanese", "こんにちは。今日はラジオの音声合成を確認します。", []int{1, 3570, 278, 1707, 7026, 291, 8463, 12863, 49215, 278}},
		{"news", "東京都では、九月七日の午後三時から新しい催しが始まります。", []int{1, 4044, 467, 275, 7520, 373, 4131, 3494, 5842, 1169, 7271, 1446, 57827, 32877, 278}},
		{"digits_and_punctuation", "AIと音楽、価格は1,234円です。", []int{1, 3792, 317, 2116, 275, 12060, 277, 273, 279, 289, 294, 27945, 278}},
		{"emoji_byte_fallback", "あははっ🤭、楽しいですね。", []int{1, 75592, 1819, 255, 174, 179, 188, 275, 86914, 278}},
		{"variant_kanji_byte_fallback", "𠮷野家と髙橋さん。", []int{1, 255, 175, 189, 198, 1603, 1387, 317, 73419, 583, 278}},
		{"spaces_preserved", " hello  world ", []int{1, 271, 15407, 271, 634, 271}},
		{"empty", "", []int{1}},
		{"single_space", " ", []int{1, 271}},
		{"repeated_spaces", "  ", []int{1, 271, 271}},
		{"newline", "\n", []int{1, 25}},
		{"newline_then_text", "\nこんにちは", []int{1, 25, 3570}},
		{"special_tokens_adjacent", "<s>hello</s>", []int{1, 1, 15407, 2}},
		{"special_tokens", "<pad><mask><cls>", []int{1, 3, 5, 6}},
		{"chat_marker", "<|assistant|>", []int{1, 8}},
		{"unicode_multi_byte", "é🤭𠮷", []int{1, 2697, 255, 174, 179, 188, 255, 175, 189, 198}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := append([]int{tok.BOSID()}, tok.Encode(tc.text)...)
			if !equalInts(got, tc.want) {
				t.Fatalf("ids mismatch: got %v want %v", got, tc.want)
			}
			ids, mask := tok.EncodePadded(tc.text, 256)
			if len(ids) != 256 || len(mask) != 256 {
				t.Fatalf("padded shape: got ids=%d mask=%d", len(ids), len(mask))
			}
			for i, want := range tc.want {
				if ids[i] != int64(want) || !mask[i] {
					t.Fatalf("active[%d]: got (%d,%v) want (%d,true)", i, ids[i], mask[i], want)
				}
			}
			for i := len(tc.want); i < len(ids); i++ {
				if ids[i] != int64(tok.PadID()) || mask[i] {
					t.Fatalf("padding[%d]: got (%d,%v) want (%d,false)", i, ids[i], mask[i], tok.PadID())
				}
			}
		})
	}
}

func TestV4BoundaryFixtures(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(file), "../../../../model/irodori-v4.1/tokenizer/tokenizer.json")
	tok, err := FromFile(path, true)
	if err != nil {
		t.Fatal(err)
	}

	for _, n := range []int{255, 256, 257} {
		t.Run("ascii_bytes_"+itoa(n), func(t *testing.T) {
			text := repeatedASCII('a', n)
			ids := append([]int{tok.BOSID()}, tok.Encode(text)...)
			if len(ids) != map[int]int{255: 52, 256: 53, 257: 53}[n] {
				t.Fatalf("%d-byte boundary token count: got %d ids=%v", n, len(ids), ids)
			}
			if ids[0] != 1 || ids[1] != map[int]int{255: 91721, 256: 351, 257: 9319}[n] {
				t.Fatalf("%d-byte boundary prefix: got %v", n, ids[:minInt(len(ids), 3)])
			}
		})
	}
}

func TestV4TokenCountBoundaries(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(file), "../../../../model/irodori-v4.1/tokenizer/tokenizer.json")
	tok, err := FromFile(path, true)
	if err != nil {
		t.Fatal(err)
	}
	for _, n := range []int{255, 256, 257} {
		t.Run("tokens_"+itoa(n), func(t *testing.T) {
			text := repeatedString("<|assistant|>", n)
			body := tok.Encode(text)
			if len(body) != n {
				t.Fatalf("official token count mismatch: got %d want %d", len(body), n)
			}
			ids, mask := tok.EncodePadded(text, 256)
			wantActive := n + 1
			if wantActive > 256 {
				wantActive = 256
			}
			for i := 0; i < 256; i++ {
				if i < wantActive {
					if !mask[i] {
						t.Fatalf("mask[%d] false inside active prefix", i)
					}
				} else if mask[i] || ids[i] != int64(tok.PadID()) {
					t.Fatalf("padding[%d] mismatch: got (%d,%v)", i, ids[i], mask[i])
				}
			}
		})
	}
}

func TestV3GoldenPreserved(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(file), "../../../../model/irodori-v3/tokenizer.json")
	tok, err := FromFile(path, true)
	if err != nil {
		t.Fatal(err)
	}
	if tok.PadID() != 4 {
		t.Fatalf("v3 pad id changed: got %d", tok.PadID())
	}
	got := append([]int{tok.BOSID()}, tok.Encode("こんにちは。今日はラジオの音声合成を確認します。")...)
	want := []int{1, 98912, 65676, 64188, 28998, 77546, 67699, 29083, 74137, 78453}
	if !equalInts(got, want) {
		t.Fatalf("v3 ids changed: got %v want %v", got, want)
	}
}

func TestEncodePaddedCheckedRejectsInvalidLength(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(file), "../../../../model/irodori-v4.1/tokenizer/tokenizer.json")
	tok, err := FromFile(path, true)
	if err != nil {
		t.Fatal(err)
	}
	if _, _, err := tok.EncodePaddedChecked("hello", 0); err == nil {
		t.Fatal("expected max_length validation error")
	}
}

func equalInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func repeatedASCII(ch byte, n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = ch
	}
	return string(b)
}

func repeatedString(s string, n int) string {
	var b strings.Builder
	b.Grow(len(s) * n)
	for i := 0; i < n; i++ {
		b.WriteString(s)
	}
	return b.String()
}

func itoa(n int) string {
	return fmt.Sprintf("%d", n)
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}
