// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNextItem(arg1) {
  return window['go']['main']['App']['GetNextItem'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PrefetchTalk() {
  return window['go']['main']['App']['PrefetchTalk']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SkipCurrent(arg1) {
  return window['go']['main']['App']['SkipCurrent'](arg1);
}

export function UpdateStableAudio3Genre(arg1) {
  return window['go']['main']['App']['UpdateStableAudio3Genre'](arg1);
}
