// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetNextItem(arg1:domain.NextItemRequest):Promise<domain.PlayableItem>;

export function GetStatus():Promise<domain.AppStatus>;

export function LoadConfig():Promise<domain.AppConfig>;

export function PrefetchTalk():Promise<void>;

export function SaveConfig(arg1:domain.AppConfig):Promise<void>;

export function ScanGenres():Promise<Array<string>>;

export function SkipCurrent(arg1:domain.SkipRequest):Promise<domain.PlayableItem>;
